create table if not exists DOCTOR
(
    ID BIGINT identity constraint DOCTOR_PK primary key,
    FIRSTNAME      VARCHAR(35) NOT NULL,
    LASTNAME       VARCHAR(35) NOT NULL,
    PATRONYMIC     VARCHAR(35) NOT NULL,
    SPECIALIZATION VARCHAR(35) NOT NULL
);
create table if not exists PATIENT
(
    ID BIGINT identity constraint PATIENT_PK primary key,
    FIRSTNAME  VARCHAR(35) NOT NULL,
    LASTNAME   VARCHAR(35) NOT NULL,
    PATRONYMIC VARCHAR(35) NOT NULL,
    PHONE      VARCHAR(35) NOT NULL
);
create table if not exists RECIPE
(
    ID BIGINT identity constraint RECIPE_PK primary key,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PATIENTID BIGINT,
    DOCTORID BIGINT,
    CREATEDATE DATE NOT NULL,
    VALIDITY DATE NOT NULL,
    STATUS VARCHAR(35) NOT NULL,
    FOREIGN KEY (DOCTORID) REFERENCES DOCTOR (ID),
    FOREIGN KEY (PATIENTID) REFERENCES PATIENT (ID)
);